name: Bug report
description: Report a reproducible issue in the replay harness.
title: "[Bug]: "
labels:
  - bug
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting a bug. Please include a minimal reproduction.
  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: What happened and why is it a problem?
      placeholder: The gate accepted a candidate that should fail because...
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Reproduction steps
      description: Exact commands and files used.
      placeholder: |
        1. npm ci
        2. npm run ci:candidates -- ...
        3. Observe ...
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      description: What should have happened?
    validations:
      required: true
  - type: textarea
    id: actual
    attributes:
      label: Actual behavior
      description: What happened instead?
    validations:
      required: true
  - type: input
    id: environment
    attributes:
      label: Environment
      description: Node version, OS, and branch/commit.
      placeholder: "Node 20.11, macOS 14.5, main@abc123"
    validations:
      required: true
